# docs: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

name: Build and Test

on:
  push:
    branches: ["main"]
  pull_request:
  merge_group:

  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

env:
  CARGO_INCREMENTAL: 0
  SCCACHE_VERSION: 0.10.0
  SCCACHE_GHA_CACHE_TO: sccache-caliptra-sw
  SCCACHE_GHA_CACHE_FROM: sccache-caliptra-sw
  SCCACHE_GHA_ENABLED: "on"
  # CPTRA_COVERAGE_PATH: /tmp

  # Compiler warnings should fail to compile
  EXTRA_CARGO_CONFIG: "target.'cfg(all())'.rustflags = [\"-Dwarnings\"]"

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Test commit name
        run: |
          echo "Build-Test: release_ref=$(git rev-parse HEAD)"

      - name: Run precheckin checks
        run: cargo xtask precheckin

  build:
    needs: lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Test commit name
        run: |
          echo "Build-Test: release_ref=$(git rev-parse HEAD)"

      - name: Build
        run: cargo xtask ci build

      # As fuzzing targets are not part of the workspace, perform their tests explicitly.
      - name: Build test fuzzing targets
        # Intermittently fails and is too slow
        if: false
        run: |
          rustup toolchain install nightly-2023-04-15
          cargo +nightly-2023-04-15 install cargo-fuzz cargo-afl
          for target in dpe/dpe/fuzz/ drivers/fuzz/ image/verify/fuzz/ x509/fuzz/; do
            pushd $target; \
            cargo fmt --check; \
            # TODO: Depends on https://github.com/chipsalliance/caliptra-sw/issues/681
            #cargo clippy; \
            cargo +nightly-2023-04-15 fuzz build --features libfuzzer-sys; \
            cargo +nightly-2023-04-15 afl build --features afl; \
            popd; \
          done
          for target in drivers/fuzz/ image/verify/fuzz/; do
            pushd $target; \
            cargo +nightly-2023-04-15 fuzz build --features libfuzzer-sys,struct-aware; \
            cargo +nightly-2023-04-15 afl build --features afl,struct-aware; \
            popd; \
          done

  test_unit:
    needs: lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Run tests
        run: cargo xtask ci test unit

  test_compliance:
    needs: lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Run emulator conformance tests
        run: |
          sudo apt-get update -qy && sudo apt-get install gcc-riscv64-unknown-elf binutils-riscv64-unknown-elf
          cargo xtask ci test compliance

  test_rom:
    needs: lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Run ROM tests
        run: cargo xtask ci test rom

  test_integration:
    needs: lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Install required packages
        run: |
          sudo apt-get update -qy && sudo apt-get install golang-1.21-go

      - name: Run integration tests
        run: cargo xtask ci test integration

  all_checks_passed:
    needs: [build, test_unit, test_compliance, test_rom, test_integration]
    runs-on: ubuntu-24.04
    steps:
      - name: All checks passed
        run: echo "All checks passed"
