
name: Build FPGA SD image

on:
  pull_request:
    paths:
      - "ci-tools/fpga-image/**"

  push:
    branches: ["main", "carl/vck190-build"]

  schedule:
    # 5:13 AM PST tuesday, thursday
    - cron: '13 13 * * 2,4'

  workflow_call:
  workflow_dispatch:

jobs:
  build_sd_image:
    runs-on: [e2-standard-32, vck190-tools]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install pre-requisites
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get -y install debootstrap binfmt-support qemu-user-static u-boot-tools gcc-aarch64-linux-gnu
          rustup target add aarch64-unknown-linux-gnu
          sudo apt install gcc libncurses-dev zlib1g:i386 zlib1g-dev net-tools xterm autoconf libtool texinfo gcc-multilib build-essential device-tree-compiler xvfb apt-transport-https ca-certificates gnupg curl -y

      - name: Mount FPGA tools
        run: |
          echo "Starting work"
          sudo mkdir /vck190-tools
          sudo mount UUID=249f0fea-68c1-4e14-af09-5294e50e20b1 /vck190-tools/
          ls /vck190-tools/caliptra-bitstreams/20250701

      - name: Build SD image
        run: |
          source /vck190-tools/petalinux-tool/settings.sh

          pushd hw/fpga/petalinux_project
          petalinux-config --get-hw-description /vck190-tools/caliptra-bitstreams/20250701/caliptra_fpga.xsa --silentconfig
          petalinux-build  && petalinux-package --boot --format BIN --plm --psmfw --u-boot --dtb --force
          pushd images/linux

          tar -cvf vck190-kernel.tar.gz BOOT.BIN Image image.ub boot.scr system.dts system.dtb
          mv vck190-kernel.tar.gz /tmp/vck190-kernel.tar.gz
          popd
          petalinux-build -c io-module
          IO_MODULE_PATH=$(find . -name 'io-module.ko')
          mv $IO_MODULE_PATH /tmp/io-module.ko
          popd

          cd ci-tools/fpga-image
          sudo bash build.sh

      - name: 'Upload image as artifact'
        uses: actions/upload-artifact@v4
        with:
          name: caliptra-fpga-image
          path: ci-tools/fpga-image/out/image.img
          retention-days: 90
